export const GET_CHECKIN_DATA = 'GET_CHECKIN_DATA';
export const GET_CHECKIN_DATA_SUCCESS = 'GET_CHECKIN_DATA_SUCCESS';
export const GET_CHECKIN_DATA_FAIL = 'GET_CHECKIN_DATA_FAIL';

export const SAVE_CHECKIN_DATA = "SAVE_CHECKIN_DATA";
export const SAVE_CHECKIN_DATA_SUCCESS = "SAVE_CHECKIN_DATA_SUCCESS";
export const SAVE_CHECKIN_DATA_FAIL = "SAVE_CHECKIN_DATA_FAIL";

export const REQUEST_PDF = "REQUEST_PDF";
export const REQUEST_PDF_SUCCESS = "REQUEST_PDF_SUCCESS";
export const REQUEST_PDF_FAIL = "REQUEST_PDF_FAIL";