export const GET_SHIPMENT_DATA = 'GET_SHIPMENT_DATA';
export const GET_SHIPMENT_DATA_SUCCESS = 'GET_SHIPMENT_DATA_SUCCESS';
export const GET_SHIPMENT_DATA_FAIL = 'GET_SHIPMENT_DATA_FAIL';

export const ADD_RECORD = 'ADD_RECORD';
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAIL = 'ADD_RECORD_FAIL';
